[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts", 
"@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", 
"@uniswapPeriphery/contracts=lib/v3-periphery/contracts",
"@uniswapCore/contracts=lib/v3-core/contracts"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
