[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"

remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts", 
"@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", 
"@uniswap/v3-periphery/contracts=lib/v3-periphery/contracts",
"@uniswap/v3-core/contracts=lib/v3-core/contracts"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
